version: '3.8'

services:
  traefik:
    image: traefik:v2.9 
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      # Logs
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--log.format=json"
    ports:
      - "80:80"
      # Used for the web interface of traefik
      #- "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/log:/logs

  dice_api:
    build: 
      context: "../Dynamic HTTP Server/"
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dice_api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.dice_api.entrypoints=web"

  static:
    build: 
      context: "../Static HTTP server/"
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`static.localhost`)"
      - "traefik.http.routers.static.entrypoints=web"
  
  load_balancer_rr:
    build: 
      context: "../Load Balancing/"
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.load_balancer_rr.rule=Host(`lb.localhost`)"
      - "traefik.http.routers.load_balancer_rr.entrypoints=web"
  load_balancer_sticky:
    build: 
      context: "../Load Balancing/"
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.load_balancer_sticky.rule=Host(`sticky.localhost`)"
      - "traefik.http.routers.load_balancer_sticky.entrypoints=web"
      - "traefik.http.services.load_balancer_sticky.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.load_balancer_sticky.loadBalancer.sticky.cookie.name=sticky_load_balancer"
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`mangement.localhost`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"